stages:
- build
- release

build:
  image: ${REGISTRY_URL}/factory-ci-runner:factory-ci
  stage: build
  script:
    - make -C .docker build deliver
  environment:
    name: snap
  only:
    refs:
      - tags
      - main
  artifacts:
    paths:
      - ".docker/factory.manifest"
  tags:
    - infrav3-dind

release:
  stage: release
  script: 
    - release-image pg-event-server
  environment:
    name: production
  artifacts:
    paths:
      - ".docker/factory.manifest"
  when: manual
  only:
    refs:
      - tags
  tags:
    - infrav3-dind
  variables:
    FACTORY_MANIFEST: ".docker/factory.manifest"
