stages:
- test
- build
- release

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo

cache:
  paths:
    - $CI_PROJECT_DIR/.cargo

test:
  stage: test
  image: ${REGISTRY_URL}/factory-ci-runner:rust-bullseye
  script:
    - cp pg-client-config/fixtures/passfile.conf.in pg-client-config/fixtures/passfile.conf
    - chmod 0600 pg-client-config/fixtures/passfile.conf
    - cargo test
  environment:
    name: snap
  tags:
    - infrav3-plain

dev:docker:
  image: ${REGISTRY_URL}/factory-ci-runner:build-package
  stage: build
  script:
    - make -C .docker build deliver
  environment:
    name: snap
  only:
    refs:
      - tags
      - main
  tags:
    - infrav3-dind

release:docker:
  stage: release
  script: 
    - make -C .docker build deliver
    - release-image pg-event-server
  environment:
    name: production
  artifacts:
    paths:
      - ".docker/factory.manifest"
  when: manual
  only:
    refs:
      - tags
  tags:
    - infrav3-dind
  variables:
    FACTORY_MANIFEST: ".docker/factory.manifest"

package:deb:
  stage: release
  image: ${REGISTRY_URL}/factory-ci-runner:rust-bullseye
  script:
    - cargo deb -p pg-event-server
    - cp -v target/debian/*.deb /srv/storage/debs/
  environment:
    name: snap
  only:
    refs:
      - tags
  tags:
    - infrav3-plain

