[package]
name = "pg-event-listener"
version = "0.1.0"
edition = "2021"
description = "Tools for listening to Postgres events"

[dependencies]
tokio-postgres = { version = "0.7" }
tokio = { version = "1", features = ["full"] }
thiserror = "1.0"
futures = "0.3"
