[package]
name = "pg-event-server"
version = "0.1.0"
edition = "2021"
description = "Postgres NOTIFY/SSE server"

[dependencies]
pg-event-listener = { path = "../pg-event-listener" }
pg-config = { path = "../pg-config" }
tokio-postgres = "0.7"
actix-web = { version = "4", features = ["rustls"] }
actix-web-lab = "0.19"
tokio = "1"
log = "0.4"
env_logger = "0.10"
clap = { version = "4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.7"
thiserror = "1.0"
lazy_static = "1"
futures = "0.3"
uuid = { version = "1.3", features = ["v4", "fast-rng"] }
glob = "0.3"
num_cpus = "1"
postgres-openssl = { version = "0.5", optional = true }
openssl = { version = "0.10", optional = true }
tokio-postgres-rustls = { version = "0.9", optional = true }
rustls = { version = "0.20", optional = true }
rustls-pemfile = { version = "1", optional = true }
rustls-native-certs = { version = "0.6", optional = true }

[features]
default = ["with-rustls"]
with-openssl = ["openssl", "postgres-openssl"]
with-rustls = ["rustls", "rustls-pemfile", "tokio-postgres-rustls", "rustls-native-certs"]

# see https://crates.io/crates/cargo-deb
[package.metadata.deb]
maintainer = "David Marteau <dmarteau@3liz.com>"
copyright = "2023, 3liz"
license-file = "../LICENSE-APACHE"
extended-description = """\
Proxy Postgres event as HTTP Server Send Event.
A server that subscribes to Postgres notification
and serve them to HTTP clients as Server Send Event 
(SSE). """ 
depends = "$auto"
section = "utility"
priority = "optional"
assets = [ 
    ["target/release/pg-event-server", "usr/local/bin/", "755"],
]

